### PR TITLE
Set up seed.js file, insert mock data into db.

### PR DESCRIPTION
**Pull request by sveta0112**
@ac251 Aaron, please review my database, seed.js

### CODE REVIEW

**Comment by ac251** [comment]
Looks good, only thing I see is that in the seed.js file there's some funny indentation around line 6.

**Comment by sveta0112** [comment]
@ac251 Thank you Aaron for pointing to it, i will fix it.

**Comment by ac251** [comment]
Looks good! One more thing i thought of: since you have the images hosted, do they need to be pushed to gitHub?

**Comment by sveta0112** [comment]
@ac251 Aaron, i removed that folder with images from repo, pictures are hosted in amazon s3.

**Comment by ac251** [comment]
perfect sounds good!

**Comment by sveta0112** [comment]
@ac251 Thank you!

**Pull request merged**
